### ISSUE TITLE
Plugin doesn't work with Free Gift Plugin

### ISSUE THREAD

**Issue by PDowney** [JeroenSormani/woocommerce-coupon-generator#5]
This plugin will generate the codes, but fails to enter the product id into the coupon when selecting the free gift option.

I'm happy to supply you with a copy of the free gift plugin if needed.

https://www.woothemes.com/products/free-gift-coupons/

**Comment by JeroenSormani** [comment]
Ah, that would be caused due to the new custom data not being used automatically.

It is possible to hook into the plugin and add this here: https://github.com/JeroenSormani/woocommerce-coupon-generator/blob/master/includes/admin/wccg-core-functions.php#L74

For now the plugin won't support the Free Gift Coupons plugin until there's a bigger demand for it ;-)
